
development:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: rainbow_popcorn_development
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: rainbow_popcorn_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: rainbow_popcorn_production
  pool: 5
  timeout: 5000
